version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
    tty: true # -t option in docker
    stdin_open: true # -i option in docker
    hostname: about-domain-queries
    user: ${CURRENT_USER}
    volumes:
      - ./project/:/usr/src/myapp
